savings-goal:
  minimum-days-for-withdrawal: 30
mint:
  email:
    system-admin: devops@bankwithmint.com
sentry:
  dsn: https://970446a3125a46c5a6f8afdacc007764@o555418.ingest.sentry.io/5693117
  attach-server-name: true
  server-name: savings-service
  environment: production
  enable-tracing: false
  traces-sample-rate: 0.3
