apiVersion: v1
kind: Service
metadata:
  labels:
    com.mintfintech.service: authorization-api-gateway
  name: authorization-api-gateway
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8096
  selector:
    com.mintfintech.service: authorization-api-gateway
  sessionAffinity: None
  type: ClusterIP #NodePort
