package com.mintfintech.savingsms.domain.entities.enums;

/**
 * Created by jnwanya on
 * Thu, 20 May, 2021
 */
public enum InvestmentWithdrawalStatusConstant {
    PENDING_INVESTMENT_TO_CUSTOMER,
    PENDING_LIQUIDATE_INVESTMENT_TO_CUSTOMER,
    PENDING_LIQUIDATE_INTEREST_TO_CUSTOMER,
    PENDING_LIQUIDATE_CUSTOMER_TO_TAX,
    PENDING_INTEREST_TO_PENALTY,
    PENDING_CUSTOMER_TO_PENALTY,
    PENDING_MATURITY_INVESTMENT_TO_CUSTOMER,
    PENDING_MATURITY_INTEREST_TO_CUSTOMER,
    PENDING_MATURITY_CUSTOMER_TO_TAX,

    PROCESSING_LIQUIDATE_INVESTMENT_TO_CUSTOMER,
    PROCESSING_LIQUIDATE_INTEREST_TO_CUSTOMER,
    PROCESSING_LIQUIDATE_CUSTOMER_TO_TAX,
    PROCESSING_INTEREST_TO_PENALTY,
    PROCESSING_CUSTOMER_TO_PENALTY,
    PROCESSING_MATURITY_INVESTMENT_TO_CUSTOMER,
    PROCESSING_MATURITY_INTEREST_TO_CUSTOMER,
    PROCESSING_MATURITY_CUSTOMER_TO_TAX,

    FAILED_LIQUIDATE_INVESTMENT_TO_CUSTOMER,
    FAILED_LIQUIDATE_INTEREST_TO_CUSTOMER,
    FAILED_LIQUIDATE_CUSTOMER_TO_TAX,
    FAILED_INTEREST_TO_PENALTY,
    FAILED_CUSTOMER_TO_PENALTY,
    FAILED_MATURITY_INVESTMENT_TO_CUSTOMER,
    FAILED_MATURITY_INTEREST_TO_CUSTOMER,
    FAILED_MATURITY_CUSTOMER_TO_TAX,

    SUCCESSFUL_LIQUIDATE_INVESTMENT_TO_CUSTOMER,
    SUCCESSFUL_LIQUIDATE_INTEREST_TO_CUSTOMER,
    SUCCESSFUL_LIQUIDATE_CUSTOMER_TO_TAX,
    SUCCESSFUL_INTEREST_TO_PENALTY,
    SUCCESSFUL_CUSTOMER_TO_PENALTY,
    SUCCESSFUL_MATURITY_INVESTMENT_TO_CUSTOMER,
    SUCCESSFUL_FAILED_MATURITY_INTEREST_TO_CUSTOMER,
    SUCCESSFUL_MATURITY_CUSTOMER_TO_TAX,

    LIQUIDATE_INVESTMENT_TO_CUSTOMER,
    LIQUIDATE_INTEREST_TO_CUSTOMER,
    LIQUIDATE_CUSTOMER_TO_TAX,
    INTEREST_TO_PENALTY,
    CUSTOMER_TO_PENALTY,
    MATURITY_INVESTMENT_TO_CUSTOMER,
    MATURITY_INTEREST_TO_CUSTOMER,
    MATURITY_CUSTOMER_TO_TAX,

    PROCESSED,
    CANCELLED
}
