package com.mintfintech.savingsms.domain.entities.enums;

public enum LoanTransactionTypeConstant {

    PENDING_MINT_TO_SUSPENSE,
    PENDING_INTEREST_TO_SUSPENSE,
    PENDING_SUSPENSE_TO_CUSTOMER,
    PENDING_RECOVERY_TO_MINT,
    PENDING_SUSPENSE_TO_INCOME,
    PROCESSING_MINT_TO_SUSPENSE,
    PROCESSING_INTEREST_TO_SUSPENSE,
    PROCESSING_SUSPENSE_TO_CUSTOMER,
    PROCESSING_RECOVERY_TO_MINT,
    PROCESSING_SUSPENSE_TO_INCOME,
    FAILED_MINT_TO_SUSPENSE,
    FAILED_INTEREST_TO_SUSPENSE,
    FAILED_SUSPENSE_TO_CUSTOMER,
    FAILED_RECOVERY_TO_MINT,
    FAILED_SUSPENSE_TO_INCOME,
    PROCESSED,
    CANCELLED,
    MINT_TO_SUSPENSE,
    INTEREST_TO_SUSPENSE,
    SUSPENSE_TO_CUSTOMER,
    CUSTOMER_TO_RECOVERY,
    RECOVERY_TO_MINT,
    SUSPENSE_TO_INCOME
}
