package com.mintfintech.savingsms.domain.entities.enums;

/**
 * Created by jnwanya on
 * Tue, 07 Apr, 2020
 */
public enum  WithdrawalRequestStatusConstant {
    PENDING_INTEREST_CREDIT,
    PROCESSING_INTEREST_CREDIT,
    PROCESSED_INTEREST_CREDIT,
    INTEREST_CREDITING_FAILED,

    PENDING_SAVINGS_CREDIT,
    PROCESSING_SAVINGS_CREDIT,
    SAVINGS_CREDITING_FAILED,

    PENDING_TAX_DEBIT,
    PROCESSING_TAX_DEBIT,
    TAX_DEBIT_FAILED,
    PROCESSED_TAX_DEBIT,

    PENDING_FUND_DISBURSEMENT,
    PROCESSING_FUND_DISBURSEMENT,
    FUND_DISBURSEMENT_FAILED,
    PROCESSED,
    CANCELLED
}
